image: gradle:6.0-jdk11

stages:
  - build
  - validate
  - test
  - coverage

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

checkStyle:
  stage: validate
  script: gradle checkstyleMain
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/

test:
  stage: test
  artifacts:
    paths:
     - build/reports/jacoco/test
  script:
    - gradle test

coverage:
  stage: coverage
  dependencies:
    - test
  script:
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/",
      instructions, "instructions covered"; print 100*covered/instructions, "%
      covered" }' build/reports/jacoco/test/jacocoTestReport.csv
    # - aggregate=$(awk -F"," '{ branches += $6 + $7; covered += $7 } END { print "\nAGGREGATE COVERAGE REPORT"; print covered, "/", branches, "branches covered"; print int(100*covered/branches), "%% covered\n---------------------------\n" }' target/site/jacoco-aggregate/jacoco.csv)
#    - printf "$coverage"
  coverage: '/Total.*?([0-9]{1,3})%/'

